In [4]:
import numpy as np
def convert(arr):
    for i in range(len(arr)):
        arr[i]=abs(arr[i])
    return arr
def convert_input(arr):
    l=[]
    for i in range(len(arr)):
        try:
            l.append(int(arr[i]))
        except ValueError:
            pass
    size=int(np.sqrt(len(l)))
    return np.array(l).reshape(size, size)    
def printing_inversions(arr):
    for i in range(len(arr)):
        arr[i][i]=1
        print('inversion '+str(i+1)+' ')
        print(arr)
        eigvls=np.linalg.eigvals(arr)
        char_poly=convert(np.poly(arr))
        print('sum of absolute values of characteristic polynomial coefficients is ', sum(char_poly))
        print('Maximum Absolute value of characteristic polynomial coefficients is ', max(char_poly))      
        s=0
        for j in eigvls:
            s+=abs(j)
        print('sum of absolute eigenvalues is ', s)
        print('absolute value of determinant of the given matrix is ', abs(np.linalg.det(arr)))
        arr[i][i]=0
n=int(input('enter no of matrices u need to calculate eigenvalues for '))
for i in range(1, n+1):
    matrix=input('enter the matrix ')
    arr=convert_input(matrix)
    eigvls=np.linalg.eigvals(arr)
    char_poly=convert(np.poly(arr))
    print('parent matrix ')
    print(arr)
    print('sum of absolute values of characteristic polynomial coefficients is ', sum(char_poly))
    print('Maximum Absolute value of characteristic polynomial coefficients is ', max(char_poly))      
    s=0
    for j in eigvls:
        s+=abs(j)
    print('sum of absolute eigenvalues is ', s)
    print('absolute value of determinant of the given matrix is ', abs(np.linalg.det(arr)))
    printing_inversions(arr)
    print('Matrix no ')
    
    

enter no of matrices u need to calculate eigenvalues for 1
enter the matrix 0 1 0 1 0 1 1 0 1 0 0 0 0 1 0 1 0 0 1 0 1 0 1 0 0 0 0 1 0 1 1 0 0 0 1 0
parent matrix 
[[0 1 0 1 0 1]
 [1 0 1 0 0 0]
 [0 1 0 1 0 0]
 [1 0 1 0 1 0]
 [0 0 0 1 0 1]
 [1 0 0 0 1 0]]
sum of absolute values of characteristic polynomial coefficients is  16.0
Maximum Absolute value of characteristic polynomial coefficients is  7.000000000000002
sum of absolute eigenvalues is  7.656854249492381
absolute value of determinant of the given matrix is  1.0
inversion 1 
[[1 1 0 1 0 1]
 [1 0 1 0 0 0]
 [0 1 0 1 0 0]
 [1 0 1 0 1 0]
 [0 0 0 1 0 1]
 [1 0 0 0 1 0]]
sum of absolute values of characteristic polynomial coefficients is  24.000000000000032
Maximum Absolute value of characteristic polynomial coefficients is  7.0000000000000115
sum of absolute eigenvalues is  7.902737249379324
absolute value of determinant of the given matrix is  1.0
inversion 2 
[[0 1 0 1 0 1]
 [1 1 1 0 0 0]
 [0 1 0 1 0 0]
 [1 0 1 0 1 0]
 [0 0 0 1 0 1]
 

In [ ]:
print(len(input().split()))

In [3]:
!jt -t chesterish